from unittest import TestCase


class TestVertex(TestCase): ...


class TestEdge(TestCase): ...


class TestFlowGraph(TestCase):
    def test_add_vertex(self): ...

    def test_remove_vertex(self): ...

    def test_add_edge(self): ...

    def test_remove_edge(self): ...

    def test_neighbours(self): ...

    def test_edge_between(self): ...
