from unittest import TestCase

class TestMaxFlow(TestCase):

    def test_edmunds_karp(self): ...

    def test_augmenting_path(self): ...

    def test_bottleneck(self): ...

    def test_augment_flow(self): ...

    def test_bfs(self): ...

class TestSettle(TestCase):
    def test_simplify_debt(self): ...